"""Settings and service control for fail2ban module."""

import os

from ui.components import (
    console,
    clear_screen,
    show_header,
    show_panel,
    show_success,
    show_error,
    show_warning,
    show_info,
    press_enter_to_continue,
)
from ui.menu import confirm_action, text_input, run_menu_loop, select_from_list
from utils.shell import (
    run_command_realtime,
    service_control,
    require_root,
)

from .common import (
    is_fail2ban_installed,
    is_fail2ban_running,
    detect_services,
    JAIL_LOCAL,
    DEFAULT_BANTIME,
    DEFAULT_FINDTIME,
    DEFAULT_MAXRETRY,
)


def show_menu():
    """Display settings menu."""
    def get_status():
        if is_fail2ban_running():
            return "[green]Running[/green]"
        elif is_fail2ban_installed():
            return "[red]Stopped[/red]"
        return "[dim]Not installed[/dim]"
    
    def get_options():
        return [
            ("global", "1. Global Ban Settings"),
            ("recidive", "2. Recidive Settings"),
            ("service", "3. Service Control"),
            ("back", "← Back"),
        ]
    
    handlers = {
        "global": configure_global_settings,
        "recidive": configure_recidive,
        "service": service_control_menu,
    }
    
    run_menu_loop("Settings", get_options, handlers, get_status)


def install_fail2ban():
    """Install Fail2ban with auto-detected jail configuration."""
    clear_screen()
    show_header()
    show_panel("Install Fail2ban", title="Fail2ban", style="cyan")
    
    if is_fail2ban_installed():
        show_info("Fail2ban is already installed.")
        
        if is_fail2ban_running():
            console.print("[dim]Service is running.[/dim]")
        else:
            if confirm_action("Start Fail2ban service?"):
                service_control("fail2ban", "start")
                show_success("Fail2ban started!")
        
        press_enter_to_continue()
        return True
    
    detected = detect_services()
    
    console.print("[bold]Fail2ban will protect against brute force attacks.[/bold]")
    console.print()
    console.print("[bold]Detected services to protect:[/bold]")
    
    if detected['ssh']:
        console.print("  [green]✓[/green] SSH (sshd)")
    if detected['nginx']:
        console.print("  [green]✓[/green] Nginx (http-auth, botsearch)")
    if detected['apache']:
        console.print("  [green]✓[/green] Apache (http-auth)")
    if detected['postfix']:
        console.print("  [green]✓[/green] Postfix (mail)")
    if detected['dovecot']:
        console.print("  [green]✓[/green] Dovecot (imap/pop3)")
    
    if not any(detected.values()):
        console.print("  [dim]No services detected (will enable sshd by default)[/dim]")
    
    console.print()
    console.print(f"[dim]Default settings: bantime={DEFAULT_BANTIME}, maxretry={DEFAULT_MAXRETRY}[/dim]")
    console.print()
    
    if not confirm_action("Install and configure Fail2ban?"):
        show_warning("Cancelled.")
        press_enter_to_continue()
        return False
    
    try:
        require_root()
    except PermissionError:
        press_enter_to_continue()
        return False
    
    show_info("Installing Fail2ban...")
    
    returncode = run_command_realtime(
        "apt install -y fail2ban",
        "Installing Fail2ban..."
    )
    
    if returncode != 0:
        show_error("Failed to install Fail2ban.")
        press_enter_to_continue()
        return False
    
    show_info("Configuring Fail2ban...")
    _create_initial_config(detected)
    
    service_control("fail2ban", "start")
    service_control("fail2ban", "enable")
    
    if is_fail2ban_running():
        show_success("Fail2ban installed and running!")
        console.print()
        console.print("[dim]Use Dashboard to see status.[/dim]")
    else:
        show_warning("Fail2ban installed but service may not be running.")
    
    press_enter_to_continue()
    return True


def _create_initial_config(detected_services):
    """Create initial jail.local configuration."""
    config = f"""# Fail2ban local configuration
# Generated by vexo

[DEFAULT]
bantime = {DEFAULT_BANTIME}
findtime = {DEFAULT_FINDTIME}
maxretry = {DEFAULT_MAXRETRY}
banaction = iptables-multiport

"""
    
    config += """[sshd]
enabled = true
port = ssh
filter = sshd
logpath = /var/log/auth.log
maxretry = 5

"""
    
    if detected_services.get('nginx'):
        config += """[nginx-http-auth]
enabled = true
port = http,https
filter = nginx-http-auth
logpath = /var/log/nginx/error.log

[nginx-botsearch]
enabled = true
port = http,https
filter = nginx-botsearch
logpath = /var/log/nginx/access.log

"""
    
    if detected_services.get('apache'):
        config += """[apache-auth]
enabled = true
port = http,https
filter = apache-auth
logpath = /var/log/apache2/error.log

"""
    
    if detected_services.get('postfix'):
        config += """[postfix]
enabled = true
port = smtp,465,submission
filter = postfix
logpath = /var/log/mail.log

[postfix-sasl]
enabled = true
port = smtp,465,submission
filter = postfix-sasl
logpath = /var/log/mail.log

"""
    
    if detected_services.get('dovecot'):
        config += """[dovecot]
enabled = true
port = pop3,pop3s,imap,imaps
filter = dovecot
logpath = /var/log/mail.log

"""
    
    try:
        with open(JAIL_LOCAL, "w") as f:
            f.write(config)
        return True
    except Exception as e:
        show_error(f"Failed to create config: {e}")
        return False


def configure_global_settings():
    """Configure global ban settings."""
    clear_screen()
    show_header()
    show_panel("Global Ban Settings", title="Settings", style="cyan")
    
    current = _get_current_settings()
    
    console.print("[bold]Current Settings:[/bold]")
    console.print(f"  Ban Time:   {current.get('bantime', DEFAULT_BANTIME)}")
    console.print(f"  Find Time:  {current.get('findtime', DEFAULT_FINDTIME)}")
    console.print(f"  Max Retry:  {current.get('maxretry', DEFAULT_MAXRETRY)}")
    console.print()
    
    bantime = text_input(
        title="Ban Time",
        message="Enter ban time (e.g., 1h, 30m, 1d):",
        default=current.get('bantime', DEFAULT_BANTIME)
    )
    
    if not bantime:
        show_warning("Cancelled.")
        press_enter_to_continue()
        return
    
    findtime = text_input(
        title="Find Time",
        message="Enter find time (e.g., 10m, 1h):",
        default=current.get('findtime', DEFAULT_FINDTIME)
    )
    
    if not findtime:
        show_warning("Cancelled.")
        press_enter_to_continue()
        return
    
    maxretry = text_input(
        title="Max Retry",
        message="Enter max retry count:",
        default=current.get('maxretry', DEFAULT_MAXRETRY)
    )
    
    if not maxretry:
        show_warning("Cancelled.")
        press_enter_to_continue()
        return
    
    try:
        require_root()
    except PermissionError:
        press_enter_to_continue()
        return
    
    success = _update_settings(bantime, findtime, maxretry)
    
    if success:
        service_control("fail2ban", "reload")
        show_success("Settings updated!")
    else:
        show_error("Failed to update settings.")
    
    press_enter_to_continue()


def configure_recidive():
    """Configure recidive jail for repeat offenders."""
    clear_screen()
    show_header()
    show_panel("Recidive Settings", title="Settings", style="cyan")
    
    show_info("Recidive settings will be implemented in Phase 9.")
    press_enter_to_continue()


def service_control_menu():
    """Service control menu."""
    clear_screen()
    show_header()
    show_panel("Service Control", title="Settings", style="cyan")
    
    if is_fail2ban_running():
        console.print("Status: [green]● Running[/green]")
    else:
        console.print("Status: [red]● Stopped[/red]")
    
    console.print()
    
    options = []
    if is_fail2ban_running():
        options.extend([
            "Stop Service",
            "Restart Service",
            "Reload Config",
        ])
    else:
        options.append("Start Service")
    
    action = select_from_list(
        title="Service Control",
        message="Select action:",
        options=options
    )
    
    if not action:
        return
    
    try:
        require_root()
    except PermissionError:
        press_enter_to_continue()
        return
    
    action_map = {
        "Stop Service": "stop",
        "Start Service": "start",
        "Restart Service": "restart",
        "Reload Config": "reload",
    }
    
    service_control("fail2ban", action_map.get(action, "status"))
    show_success(f"Service {action_map.get(action, action)} completed!")
    press_enter_to_continue()


def _get_current_settings():
    """Get current settings from jail.local."""
    settings = {}
    
    if not os.path.exists(JAIL_LOCAL):
        return settings
    
    try:
        with open(JAIL_LOCAL, 'r') as f:
            for line in f:
                line = line.strip()
                if line.startswith('bantime'):
                    settings['bantime'] = line.split('=')[-1].strip()
                elif line.startswith('findtime'):
                    settings['findtime'] = line.split('=')[-1].strip()
                elif line.startswith('maxretry'):
                    settings['maxretry'] = line.split('=')[-1].strip()
    except Exception:
        pass
    
    return settings


def _update_settings(bantime, findtime, maxretry):
    """Update settings in jail.local."""
    try:
        if os.path.exists(JAIL_LOCAL):
            with open(JAIL_LOCAL, 'r') as f:
                lines = f.readlines()
        else:
            lines = ["[DEFAULT]\n"]
        
        new_lines = []
        in_default = False
        updated = {'bantime': False, 'findtime': False, 'maxretry': False}
        
        for line in lines:
            if line.strip() == '[DEFAULT]':
                in_default = True
                new_lines.append(line)
                continue
            elif line.strip().startswith('[') and line.strip() != '[DEFAULT]':
                if in_default:
                    if not updated['bantime']:
                        new_lines.append(f"bantime = {bantime}\n")
                    if not updated['findtime']:
                        new_lines.append(f"findtime = {findtime}\n")
                    if not updated['maxretry']:
                        new_lines.append(f"maxretry = {maxretry}\n")
                in_default = False
            
            if in_default:
                if line.strip().startswith('bantime'):
                    new_lines.append(f"bantime = {bantime}\n")
                    updated['bantime'] = True
                elif line.strip().startswith('findtime'):
                    new_lines.append(f"findtime = {findtime}\n")
                    updated['findtime'] = True
                elif line.strip().startswith('maxretry'):
                    new_lines.append(f"maxretry = {maxretry}\n")
                    updated['maxretry'] = True
                else:
                    new_lines.append(line)
            else:
                new_lines.append(line)
        
        with open(JAIL_LOCAL, 'w') as f:
            f.writelines(new_lines)
        
        return True
    except Exception as e:
        show_error(f"Error: {e}")
        return False
